query ProductDetails($slug: String!, $channel: String!) {
	product(slug: $slug, channel: $channel) {
		id
		name
		slug
		description
		seoTitle
		seoDescription
		thumbnail(size: 1024, format: WEBP) {
			url
			alt
		}
		media {
			url
			alt
		}
		category {
			id
			name
		}
		attributes {
			attribute {
				slug
				name
				inputType
			}
			values {
				slug
				name
				richText
				plainText
			}
		}
		variants {
			...VariantDetails
		}
		pricing {
			priceRange {
				start {
					gross {
						amount
						currency
					}
				}
				stop {
					gross {
						amount
						currency
					}
				}
			}
		}
	}
}
