#!/usr/bin/env bash
# sync-set-icons.sh — Download MTG set icon SVGs from Scryfall to storefront/public/set-icons/
#
# Usage:
#   ./scripts/sync-set-icons.sh           # Download all missing icons
#   ./scripts/sync-set-icons.sh --force   # Re-download all icons
#
# Output:
#   storefront/public/set-icons/{code}.svg   — SVG files
#   storefront/src/lib/set-icons-manifest.ts — TypeScript Set of available codes
#
# Run this periodically to pick up new set releases.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ICON_DIR="$REPO_ROOT/storefront/public/set-icons"
MANIFEST_FILE="$REPO_ROOT/storefront/src/lib/set-icons-manifest.ts"

FORCE=false
if [[ "${1:-}" == "--force" ]]; then
  FORCE=true
fi

mkdir -p "$ICON_DIR"

echo "Fetching set list from Scryfall..."
SETS_JSON=$(curl -sf "https://api.scryfall.com/sets" --max-time 30)

# Extract set codes using python (available everywhere)
CODES=$(echo "$SETS_JSON" | python3 -c "
import json, sys
data = json.load(sys.stdin)
for s in data.get('data', []):
    code = s.get('code', '')
    if code:
        print(code)
")

TOTAL=$(echo "$CODES" | wc -l | tr -d ' ')
echo "Found $TOTAL sets on Scryfall"

DOWNLOADED=0
SKIPPED=0
FAILED=0
AVAILABLE=()

for CODE in $CODES; do
  CODE_LOWER=$(echo "$CODE" | tr '[:upper:]' '[:lower:]')
  DEST="$ICON_DIR/$CODE_LOWER.svg"

  # Skip if already exists (unless --force)
  if [[ -f "$DEST" && "$FORCE" == "false" ]]; then
    SKIPPED=$((SKIPPED + 1))
    AVAILABLE+=("$CODE_LOWER")
    continue
  fi

  # Download from Scryfall SVG CDN
  HTTP_CODE=$(curl -sf -o "$DEST" -w "%{http_code}" \
    "https://svgs.scryfall.io/sets/$CODE_LOWER.svg" \
    --max-time 10 2>/dev/null || echo "000")

  if [[ "$HTTP_CODE" == "200" ]]; then
    DOWNLOADED=$((DOWNLOADED + 1))
    AVAILABLE+=("$CODE_LOWER")
  else
    # Remove empty/partial file
    rm -f "$DEST"
    FAILED=$((FAILED + 1))
  fi

  # Rate limit: 100ms between requests
  sleep 0.1
done

echo ""
echo "=== Sync Complete ==="
echo "  Downloaded: $DOWNLOADED"
echo "  Skipped (already existed): $SKIPPED"
echo "  Failed (no SVG on Scryfall): $FAILED"
echo "  Total available: ${#AVAILABLE[@]}"

# Generate TypeScript manifest
echo "Generating manifest at $MANIFEST_FILE..."
{
  echo "// Auto-generated by scripts/sync-set-icons.sh — do not edit manually"
  echo "// Last synced: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "// Total: ${#AVAILABLE[@]} set icons"
  echo ""
  echo "export const SET_ICON_CODES = new Set(["

  # Sort and output codes
  printf '%s\n' "${AVAILABLE[@]}" | sort | while read -r code; do
    echo "  \"$code\","
  done

  echo "]);"
  echo ""
  echo "export function hasSetIcon(code: string): boolean {"
  echo "  return SET_ICON_CODES.has(code.toLowerCase());"
  echo "}"
} > "$MANIFEST_FILE"

echo "Done. Run 'git add storefront/public/set-icons/ storefront/src/lib/set-icons-manifest.ts' to commit."
